# mk42-deploy
# ansible/roles/common/tasks/pkgs.yml

- name: Install common software
  package: name="{{ item }}" state="installed"
  with_items:
    - "{{ pkgs }}"

- name: Upgrade all packages
  package:
    name: "*"
    state: "latest"
